version: 0.0.1.{build}-test

# Use default image unless needed
#os:
#- Windows Server 2012 R2

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
    TARGET: "mingw"
    ZLIB_DIR: "C:\\msys64\\MINGW64"

  - LUA: "lua 5.2 --compat none"
    TARGET: "mingw"
    ZLIB_DIR: "C:\\msys64\\MINGW64"

  - LUA: "lua 5.3 --compat none"
    TARGET: "mingw"
    ZLIB_DIR: "C:\\msys64\\MINGW64"

  - LUA: "luajit 2.1"
    TARGET: "mingw"
    ZLIB_DIR: "C:\\msys64\\MINGW64"
  
  - LUA: "lua 5.1"
    TARGET: "vs_64"
    ZLIB_DIR: "C:\\Tools\\vcpkg\\packages\\zlib_x64-windows"

  - LUA: "lua 5.2 --compat none"
    TARGET: "vs_64"
    ZLIB_DIR: "C:\\Tools\\vcpkg\\packages\\zlib_x64-windows"

  - LUA: "lua 5.3 --compat none"
    TARGET: "vs_64"
    ZLIB_DIR: "C:\\Tools\\vcpkg\\packages\\zlib_x64-windows"

  - LUA: "luajit 2.1"
    TARGET: "vs_64"
    ZLIB_DIR: "C:\\Tools\\vcpkg\\packages\\zlib_x64-windows"


install:
  - set PATH=%CD%\env\bin;C:\Python27\Scripts;C:\MinGW\bin;C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%;
  - pip install hererocks
  - hererocks env --%LUA% --target %TARGET% --luarocks latest
  - c:\tools\vcpkg\vcpkg.exe install zlib:x64-windows
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-zlib"

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks install rocks-fs --dev
- luarocks install rocks-fun --dev
- luarocks install rocks-dir --dev
- luarocks install rocks-sysdetect --dev
- luarocks make ZLIB_DIR=%ZLIB_DIR%

before_test:
- luarocks install tl

test_script:
- echo "Type check..."
- tl check src/rocks/zip.d.tl
- echo "Testing..."
- luarocks test 

after_test:
# @todo